etc/bacula/scripts/make_postgresql_tables	usr/share/bacula-director
etc/bacula/scripts/grant_postgresql_privileges usr/share/bacula-director
etc/bacula/scripts/update_postgres* usr/share/bacula-director
etc/bacula/scripts/make_catalog_backup
etc/bacula/scripts/delete_catalog_backup usr/share/bacula-common/defconfig/scripts
etc/bacula/scripts/*catalog_backup.pl
debian/additions/pgsql/make_catalog_backup_awk      etc/bacula/scripts
usr/sbin/bacula-dir
usr/sbin/dbcheck
debian/additions/pgsql/database/pgsql	usr/share/dbconfig-common/data/bacula-director-pgsql/install-dbadmin
